name: Vali Cross Compiler CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo chmod +x ./full-setup.sh
    - run: ./full-setup.sh
      timeout-minutes: 0
    - name: Create cross-compiler release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args: './cross-compiler.zip'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
