name: Vali Cross Compiler CI

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    timeout-minutes: 0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      name: Set tag value
    - run: sudo chmod +x ./full-setup.sh
      name: Prepare release script
    - run: ./full-setup.sh
      name: Build release
      timeout-minutes: 0
    - uses: ncipollo/release-action@v1
      name: Create release
      with:
        artifacts: "cross-compiler.zip"
        tag: $RELEASE_VERSION
        token: ${{ secrets.GITHUB_TOKEN }}
