name: Vali Cross Compiler CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo chmod +x ./full-setup.sh
      name: Prepare release script
    - run: ./full-setup.sh
      name: Build release
      timeout-minutes: 0
    - uses: ncipollo/release-action@v1
      name: Create release
      with:
        artifacts: "cross-compiler.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
