name: Vali Cross Compiler CI

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    timeout-minutes: 0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set tag value
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - run: sudo chmod +x ./full-setup.sh
      name: Prepare release script
    - name: Build release
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: ./full-setup.sh
      timeout-minutes: 0
    - uses: ncipollo/release-action@v1
      name: Create release
      with:
        artifacts: "cross-compiler.zip"
        tag: ${{ steps.vars.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
