name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vali-toolchain:$(date +%s)
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: fadekraft
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: dce8e094-6235-4f16-9beb-db93b0909ba1
        # Docker repository to tag the image with
        repository: valios/vali-toolchain
        # Automatically tags the built image with the git reference as per the readme
        tag_with_ref: true
